version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - funlen
    - gochecknoglobals
    - lll
    - nlreturn
    - noinlineerr
    - nolintlint
    - tagliatelle
    - varnamelen
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  default: all
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
