// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0
// 	protoc        v3.11.4
// source: emailer.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SendOneEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From     string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	FromName string `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	To       string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Subject  string `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Text     string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *SendOneEmailRequest) Reset() {
	*x = SendOneEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOneEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOneEmailRequest) ProtoMessage() {}

func (x *SendOneEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emailer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOneEmailRequest.ProtoReflect.Descriptor instead.
func (*SendOneEmailRequest) Descriptor() ([]byte, []int) {
	return file_emailer_proto_rawDescGZIP(), []int{0}
}

func (x *SendOneEmailRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendOneEmailRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *SendOneEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendOneEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendOneEmailRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendOneEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 0 — no error.
	// 1 — internal error.
	ErrorCode int64 `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
}

func (x *SendOneEmailResponse) Reset() {
	*x = SendOneEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emailer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOneEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOneEmailResponse) ProtoMessage() {}

func (x *SendOneEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emailer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOneEmailResponse.ProtoReflect.Descriptor instead.
func (*SendOneEmailResponse) Descriptor() ([]byte, []int) {
	return file_emailer_proto_rawDescGZIP(), []int{1}
}

func (x *SendOneEmailResponse) GetErrorCode() int64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

var File_emailer_proto protoreflect.FileDescriptor

var file_emailer_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x4f,
	0x6e, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x35, 0x0a,
	0x14, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x32, 0x54, 0x0a, 0x07, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x12,
	0x49, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emailer_proto_rawDescOnce sync.Once
	file_emailer_proto_rawDescData = file_emailer_proto_rawDesc
)

func file_emailer_proto_rawDescGZIP() []byte {
	file_emailer_proto_rawDescOnce.Do(func() {
		file_emailer_proto_rawDescData = protoimpl.X.CompressGZIP(file_emailer_proto_rawDescData)
	})
	return file_emailer_proto_rawDescData
}

var file_emailer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_emailer_proto_goTypes = []interface{}{
	(*SendOneEmailRequest)(nil),  // 0: proto.SendOneEmailRequest
	(*SendOneEmailResponse)(nil), // 1: proto.SendOneEmailResponse
}
var file_emailer_proto_depIdxs = []int32{
	0, // 0: proto.Emailer.SendOneEmail:input_type -> proto.SendOneEmailRequest
	1, // 1: proto.Emailer.SendOneEmail:output_type -> proto.SendOneEmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_emailer_proto_init() }
func file_emailer_proto_init() {
	if File_emailer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_emailer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOneEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emailer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOneEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emailer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emailer_proto_goTypes,
		DependencyIndexes: file_emailer_proto_depIdxs,
		MessageInfos:      file_emailer_proto_msgTypes,
	}.Build()
	File_emailer_proto = out.File
	file_emailer_proto_rawDesc = nil
	file_emailer_proto_goTypes = nil
	file_emailer_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EmailerClient is the client API for Emailer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailerClient interface {
	SendOneEmail(ctx context.Context, in *SendOneEmailRequest, opts ...grpc.CallOption) (*SendOneEmailResponse, error)
}

type emailerClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailerClient(cc grpc.ClientConnInterface) EmailerClient {
	return &emailerClient{cc}
}

func (c *emailerClient) SendOneEmail(ctx context.Context, in *SendOneEmailRequest, opts ...grpc.CallOption) (*SendOneEmailResponse, error) {
	out := new(SendOneEmailResponse)
	err := c.cc.Invoke(ctx, "/proto.Emailer/SendOneEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailerServer is the server API for Emailer service.
type EmailerServer interface {
	SendOneEmail(context.Context, *SendOneEmailRequest) (*SendOneEmailResponse, error)
}

// UnimplementedEmailerServer can be embedded to have forward compatible implementations.
type UnimplementedEmailerServer struct {
}

func (*UnimplementedEmailerServer) SendOneEmail(context.Context, *SendOneEmailRequest) (*SendOneEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOneEmail not implemented")
}

func RegisterEmailerServer(s *grpc.Server, srv EmailerServer) {
	s.RegisterService(&_Emailer_serviceDesc, srv)
}

func _Emailer_SendOneEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOneEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailerServer).SendOneEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Emailer/SendOneEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailerServer).SendOneEmail(ctx, req.(*SendOneEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Emailer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Emailer",
	HandlerType: (*EmailerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOneEmail",
			Handler:    _Emailer_SendOneEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emailer.proto",
}
